/**
 * The generic bot pattern of isbot 5.2.2 (https://github.com/omrilotan/isbot, released into the
 * public domain under the Unlicense), vendored so that `botOf` has no dependency. It says whether a
 * user agent looks automated, not which bot it is: `botOf` tries its named table first and falls
 * back to this for the long tail. Refresh it by copying `list` from a newer isbot release.
 */
export const GENERIC_BOT_PATTERNS: readonly string[] = [
  ' daum[ /]',
  ' deusu/',
  '(?:^|[^g])news(?!sapphire)',
  '(?<! channel/|google/)google(?!(?:wv|app|/google| pixel))',
  '(?<! cu)bots?(?:\\b|_)',
  '(?<!cam)scan',
  '(?<!lib)http',
  '24x7',
  ';\\s\\w+;$',
  '@[a-z][\\w-]+\\.',
  '\\(\\)',
  '\\.com\\b',
  '\\b\\w+/1\\.0;',
  '\\bbw/',
  '\\bdlc\\b',
  '\\bort/',
  '\\bperl\\b',
  '\\btime/',
  '\\|',
  '^[<\\(;]',
  '^[\\w \\.\\-\\(?:\\):%]+(?:/v?\\d+(?:\\.\\d+)?(?:\\.\\d{1,10})*?)?(?:,|$)',
  '^[\\w\\-]+/[\\w]+$',
  '^[^ ]{50,}$',
  '^\\d+\\b',
  '^\\w*search\\b',
  '^\\w+/[\\w\\(\\)]*$',
  '^\\w+/\\d\\.\\d\\s\\([\\w@]+\\)$',
  '^active',
  '^ad muncher',
  '^amaya',
  '^apache/',
  '^avsdevicesdk/',
  '^azure',
  '^biglotron',
  '^blackbox exporter',
  '^bot',
  '^clamav[ /]',
  '^claude-code/',
  '^client/',
  '^cobweb/',
  '^custom',
  '^ddg[_-]android',
  '^discourse',
  '^dispatch/\\d',
  '^downcast/',
  '^duckduckgo',
  '^email',
  '^exodusmovement',
  '^facebook',
  '^getright/',
  '^gozilla/',
  '^hobbit',
  '^hotzonu',
  '^hwcdn/',
  '^igetter/',
  '^jeode/',
  '^jetty/',
  '^jigsaw',
  '^microsoft bits',
  '^movabletype',
  '^mozilla/\\d\\.\\d\\s[\\w\\.-]+$',
  '^mozilla/\\d\\.\\d\\s\\((?:compatible;)?(?:\\s?[\\w\\d-.]+\\/\\d+\\.\\d+)?\\)$',
  '^navermailapp',
  '^netsurf',
  '^offline',
  '^openai/',
  '^owler',
  '^php',
  '^postman',
  '^ps_daily/',
  '^python',
  '^rank',
  '^read',
  '^reed',
  '^remove\\.bg/',
  '^rest',
  '^rss',
  '^snapchat',
  '^sora ',
  '^space bison',
  '^stape/',
  '^svn',
  '^swcd ',
  '^taringa',
  '^thumbor/',
  '^track',
  '^w3c',
  '^webbandit/',
  '^webcopier',
  '^wget',
  '^whatsapp',
  '^wordpress',
  '^xenu link sleuth',
  '^yahoo',
  '^yandex',
  '^zdm/\\d',
  '^zoom marketplace/',
  'abuse',
  'advisor',
  'agent\\b',
  'analyzer',
  'archive',
  'ask jeeves/teoma',
  'attracta',
  'audit',
  'bluecoat drtr',
  'browsex',
  'burpcollaborator',
  'capture',
  'catch',
  'check\\b',
  'checker',
  'chrome-lighthouse',
  'chromeframe',
  'classifier',
  'cloudflare',
  'collapsify\\b',
  'convertify',
  'cookiehubverify/',
  'crawl',
  'cursor/',
  'cypress/',
  'dareboost',
  'datanyze',
  'dejaclick',
  'detect',
  'discovery',
  'dmbrowser',
  'download',
  'exaleadcloudview',
  'feed',
  'firephp',
  'foregenix',
  'functionize',
  'grab',
  'hardenize\\b',
  'headless',
  'hotjar',
  'httrack',
  'hubspot marketing grader',
  'ibisbrowser',
  'infrawatch',
  'insight',
  'inspect',
  'iplabel',
  'java(?!;)',
  'library',
  'linkcheck',
  'linktiger',
  'mail\\.ru/',
  'manager',
  'manus-user/',
  'marketgoo/',
  'measure',
  'monitor\\b',
  'neustar wpm',
  'node\\b',
  'nutch',
  'offbyone',
  'openvas',
  'optimize',
  'pageburst',
  'pagespeed',
  'parser',
  'phantomjs',
  'pingdom',
  'playwright',
  'powermarks',
  'preview',
  'productfinder',
  'prospectingstudio',
  'proxy',
  'ptst[ /]\\d',
  'radar',
  'readable/',
  'retriever',
  'rexx;',
  'rigor',
  'rss\\b',
  'scrape',
  'securityheaders',
  'selenium',
  'server',
  'silktide',
  'sindup/',
  'sogou',
  'sparkler/',
  'speedcurve',
  'spider',
  'splash',
  'statuscake',
  'supercleaner',
  'synapse',
  'synthetic',
  'testlocally',
  'tools',
  'torrent',
  'transcoder',
  'url',
  'validator',
  'virtuoso',
  'wappalyzer',
  'watchtowr',
  'webglance',
  'webkit2png',
  'whatcms/',
  'xtate/',
];

/** One case-insensitive expression; the parts use lookbehind, which every supported runtime has. */
export const GENERIC_BOT = new RegExp(GENERIC_BOT_PATTERNS.join('|'), 'i');
