export type ISO3166CountryCode = {
  numeric: number;
  name: string;
  alpha2: string;
  alpha3: string;
};

export const ISO_3601_1: ISO3166CountryCode[] = [
  { numeric: 4, name: 'Afghanistan', alpha2: 'AF', alpha3: 'AFG' },
  { numeric: 8, name: 'Albania', alpha2: 'AL', alpha3: 'ALB' },
  { numeric: 12, name: 'Algeria', alpha2: 'DZ', alpha3: 'DZA' },
  { numeric: 16, name: 'American Samoa', alpha2: 'AS', alpha3: 'ASM' },
  { numeric: 20, name: 'Andorra', alpha2: 'AD', alpha3: 'AND' },
  { numeric: 24, name: 'Angola', alpha2: 'AO', alpha3: 'AGO' },
  { numeric: 660, name: 'Anguilla', alpha2: 'AI', alpha3: 'AIA' },
  { numeric: 10, name: 'Antarctica', alpha2: 'AQ', alpha3: 'ATA' },
  { numeric: 28, name: 'Antigua and Barbuda', alpha2: 'AG', alpha3: 'ATG' },
  { numeric: 32, name: 'Argentina', alpha2: 'AR', alpha3: 'ARG' },
  { numeric: 51, name: 'Armenia', alpha2: 'AM', alpha3: 'ARM' },
  { numeric: 533, name: 'Aruba', alpha2: 'AW', alpha3: 'ABW' },
  { numeric: 36, name: 'Australia', alpha2: 'AU', alpha3: 'AUS' },
  { numeric: 40, name: 'Austria', alpha2: 'AT', alpha3: 'AUT' },
  { numeric: 31, name: 'Azerbaijan', alpha2: 'AZ', alpha3: 'AZE' },
  { numeric: 44, name: 'Bahamas', alpha2: 'BS', alpha3: 'BHS' },
  { numeric: 48, name: 'Bahrain', alpha2: 'BH', alpha3: 'BHR' },
  { numeric: 50, name: 'Bangladesh', alpha2: 'BD', alpha3: 'BGD' },
  { numeric: 52, name: 'Barbados', alpha2: 'BB', alpha3: 'BRB' },
  { numeric: 112, name: 'Belarus', alpha2: 'BY', alpha3: 'BLR' },
  { numeric: 56, name: 'Belgium', alpha2: 'BE', alpha3: 'BEL' },
  { numeric: 84, name: 'Belize', alpha2: 'BZ', alpha3: 'BLZ' },
  { numeric: 204, name: 'Benin', alpha2: 'BJ', alpha3: 'BEN' },
  { numeric: 60, name: 'Bermuda', alpha2: 'BM', alpha3: 'BMU' },
  { numeric: 64, name: 'Bhutan', alpha2: 'BT', alpha3: 'BTN' },
  { numeric: 68, name: 'Bolivia', alpha2: 'BO', alpha3: 'BOL' },
  { numeric: 70, name: 'Bosnia and Herzegovina', alpha2: 'BA', alpha3: 'BIH' },
  { numeric: 72, name: 'Botswana', alpha2: 'BW', alpha3: 'BWA' },
  { numeric: 74, name: 'Bouvet Island', alpha2: 'BV', alpha3: 'BVT' },
  { numeric: 76, name: 'Brazil', alpha2: 'BR', alpha3: 'BRA' },
  { numeric: 86, name: 'British Indian Ocean Territory', alpha2: 'IO', alpha3: 'IOT' },
  { numeric: 96, name: 'Brunei Darussalam', alpha2: 'BN', alpha3: 'BRN' },
  { numeric: 100, name: 'Bulgaria', alpha2: 'BG', alpha3: 'BGR' },
  { numeric: 854, name: 'Burkina Faso', alpha2: 'BF', alpha3: 'BFA' },
  { numeric: 108, name: 'Burundi', alpha2: 'BI', alpha3: 'BDI' },
  { numeric: 116, name: 'Cambodia', alpha2: 'KH', alpha3: 'KHM' },
  { numeric: 120, name: 'Cameroon', alpha2: 'CM', alpha3: 'CMR' },
  { numeric: 124, name: 'Canada', alpha2: 'CA', alpha3: 'CAN' },
  { numeric: 132, name: 'Cape Verde', alpha2: 'CV', alpha3: 'CPV' },
  { numeric: 136, name: 'Cayman Islands', alpha2: 'KY', alpha3: 'CYM' },
  { numeric: 140, name: 'Central African Republic', alpha2: 'CF', alpha3: 'CAF' },
  { numeric: 148, name: 'Chad', alpha2: 'TD', alpha3: 'TCD' },
  { numeric: 152, name: 'Chile', alpha2: 'CL', alpha3: 'CHL' },
  { numeric: 156, name: 'China', alpha2: 'CN', alpha3: 'CHN' },
  { numeric: 162, name: 'Christmas Island', alpha2: 'CX', alpha3: 'CXR' },
  { numeric: 170, name: 'Colombia', alpha2: 'CO', alpha3: 'COL' },
  { numeric: 174, name: 'Comoros', alpha2: 'KM', alpha3: 'COM' },
  { numeric: 178, name: 'Congo', alpha2: 'CG', alpha3: 'COG' },
  { numeric: 180, name: 'Congo, the Democratic Republic of the', alpha2: 'CD', alpha3: 'COD' },
  { numeric: 184, name: 'Cook Islands', alpha2: 'CK', alpha3: 'COK' },
  { numeric: 188, name: 'Costa Rica', alpha2: 'CR', alpha3: 'CRI' },
  { numeric: 384, name: "Cote D'Ivoire", alpha2: 'CI', alpha3: 'CIV' }, // Corrected SQL escape '' to '
  { numeric: 191, name: 'Croatia', alpha2: 'HR', alpha3: 'HRV' },
  { numeric: 192, name: 'Cuba', alpha2: 'CU', alpha3: 'CUB' },
  { numeric: 196, name: 'Cyprus', alpha2: 'CY', alpha3: 'CYP' },
  { numeric: 203, name: 'Czech Republic', alpha2: 'CZ', alpha3: 'CZE' },
  { numeric: 208, name: 'Denmark', alpha2: 'DK', alpha3: 'DNK' },
  { numeric: 262, name: 'Djibouti', alpha2: 'DJ', alpha3: 'DJI' },
  { numeric: 212, name: 'Dominica', alpha2: 'DM', alpha3: 'DMA' },
  { numeric: 214, name: 'Dominican Republic', alpha2: 'DO', alpha3: 'DOM' },
  { numeric: 218, name: 'Ecuador', alpha2: 'EC', alpha3: 'ECU' },
  { numeric: 818, name: 'Egypt', alpha2: 'EG', alpha3: 'EGY' },
  { numeric: 222, name: 'El Salvador', alpha2: 'SV', alpha3: 'SLV' },
  { numeric: 226, name: 'Equatorial Guinea', alpha2: 'GQ', alpha3: 'GNQ' },
  { numeric: 232, name: 'Eritrea', alpha2: 'ER', alpha3: 'ERI' },
  { numeric: 233, name: 'Estonia', alpha2: 'EE', alpha3: 'EST' },
  { numeric: 231, name: 'Ethiopia', alpha2: 'ET', alpha3: 'ETH' },
  { numeric: 238, name: 'Falkland Islands (Malvinas)', alpha2: 'FK', alpha3: 'FLK' },
  { numeric: 234, name: 'Faroe Islands', alpha2: 'FO', alpha3: 'FRO' },
  { numeric: 242, name: 'Fiji', alpha2: 'FJ', alpha3: 'FJI' },
  { numeric: 246, name: 'Finland', alpha2: 'FI', alpha3: 'FIN' },
  { numeric: 250, name: 'France', alpha2: 'FR', alpha3: 'FRA' },
  { numeric: 254, name: 'French Guiana', alpha2: 'GF', alpha3: 'GUF' },
  { numeric: 258, name: 'French Polynesia', alpha2: 'PF', alpha3: 'PYF' },
  { numeric: 260, name: 'French Southern Territories', alpha2: 'TF', alpha3: 'ATF' },
  { numeric: 266, name: 'Gabon', alpha2: 'GA', alpha3: 'GAB' },
  { numeric: 270, name: 'Gambia', alpha2: 'GM', alpha3: 'GMB' },
  { numeric: 268, name: 'Georgia', alpha2: 'GE', alpha3: 'GEO' },
  { numeric: 276, name: 'Germany', alpha2: 'DE', alpha3: 'DEU' },
  { numeric: 288, name: 'Ghana', alpha2: 'GH', alpha3: 'GHA' },
  { numeric: 292, name: 'Gibraltar', alpha2: 'GI', alpha3: 'GIB' },
  { numeric: 300, name: 'Greece', alpha2: 'GR', alpha3: 'GRC' },
  { numeric: 304, name: 'Greenland', alpha2: 'GL', alpha3: 'GRL' },
  { numeric: 308, name: 'Grenada', alpha2: 'GD', alpha3: 'GRD' },
  { numeric: 312, name: 'Guadeloupe', alpha2: 'GP', alpha3: 'GLP' },
  { numeric: 316, name: 'Guam', alpha2: 'GU', alpha3: 'GUM' },
  { numeric: 320, name: 'Guatemala', alpha2: 'GT', alpha3: 'GTM' },
  { numeric: 324, name: 'Guinea', alpha2: 'GN', alpha3: 'GIN' },
  { numeric: 624, name: 'Guinea-Bissau', alpha2: 'GW', alpha3: 'GNB' },
  { numeric: 328, name: 'Guyana', alpha2: 'GY', alpha3: 'GUY' },
  { numeric: 332, name: 'Haiti', alpha2: 'HT', alpha3: 'HTI' },
  { numeric: 334, name: 'Heard Island and Mcdonald Islands', alpha2: 'HM', alpha3: 'HMD' },
  { numeric: 336, name: 'Holy See (Vatican City State)', alpha2: 'VA', alpha3: 'VAT' },
  { numeric: 340, name: 'Honduras', alpha2: 'HN', alpha3: 'HND' },
  { numeric: 344, name: 'Hong Kong', alpha2: 'HK', alpha3: 'HKG' },
  { numeric: 348, name: 'Hungary', alpha2: 'HU', alpha3: 'HUN' },
  { numeric: 352, name: 'Iceland', alpha2: 'IS', alpha3: 'ISL' },
  { numeric: 356, name: 'India', alpha2: 'IN', alpha3: 'IND' },
  { numeric: 360, name: 'Indonesia', alpha2: 'ID', alpha3: 'IDN' },
  { numeric: 364, name: 'Iran, Islamic Republic of', alpha2: 'IR', alpha3: 'IRN' },
  { numeric: 368, name: 'Iraq', alpha2: 'IQ', alpha3: 'IRQ' },
  { numeric: 372, name: 'Ireland', alpha2: 'IE', alpha3: 'IRL' },
  { numeric: 376, name: 'Israel', alpha2: 'IL', alpha3: 'ISR' },
  { numeric: 380, name: 'Italy', alpha2: 'IT', alpha3: 'ITA' },
  { numeric: 388, name: 'Jamaica', alpha2: 'JM', alpha3: 'JAM' },
  { numeric: 392, name: 'Japan', alpha2: 'JP', alpha3: 'JPN' },
  { numeric: 400, name: 'Jordan', alpha2: 'JO', alpha3: 'JOR' },
  { numeric: 398, name: 'Kazakhstan', alpha2: 'KZ', alpha3: 'KAZ' },
  { numeric: 404, name: 'Kenya', alpha2: 'KE', alpha3: 'KEN' },
  { numeric: 296, name: 'Kiribati', alpha2: 'KI', alpha3: 'KIR' },
  { numeric: 408, name: "Korea, Democratic People's Republic of", alpha2: 'KP', alpha3: 'PRK' }, // Corrected
  { numeric: 410, name: 'Korea, Republic of', alpha2: 'KR', alpha3: 'KOR' },
  { numeric: 414, name: 'Kuwait', alpha2: 'KW', alpha3: 'KWT' },
  { numeric: 417, name: 'Kyrgyzstan', alpha2: 'KG', alpha3: 'KGZ' },
  { numeric: 418, name: "Lao People's Democratic Republic", alpha2: 'LA', alpha3: 'LAO' }, // Corrected
  { numeric: 428, name: 'Latvia', alpha2: 'LV', alpha3: 'LVA' },
  { numeric: 422, name: 'Lebanon', alpha2: 'LB', alpha3: 'LBN' },
  { numeric: 426, name: 'Lesotho', alpha2: 'LS', alpha3: 'LSO' },
  { numeric: 430, name: 'Liberia', alpha2: 'LR', alpha3: 'LBR' },
  { numeric: 434, name: 'Libyan Arab Jamahiriya', alpha2: 'LY', alpha3: 'LBY' },
  { numeric: 438, name: 'Liechtenstein', alpha2: 'LI', alpha3: 'LIE' },
  { numeric: 440, name: 'Lithuania', alpha2: 'LT', alpha3: 'LTU' },
  { numeric: 442, name: 'Luxembourg', alpha2: 'LU', alpha3: 'LUX' },
  { numeric: 446, name: 'Macao', alpha2: 'MO', alpha3: 'MAC' },
  { numeric: 807, name: 'North Macedonia', alpha2: 'MK', alpha3: 'MKD' },
  { numeric: 450, name: 'Madagascar', alpha2: 'MG', alpha3: 'MDG' },
  { numeric: 454, name: 'Malawi', alpha2: 'MW', alpha3: 'MWI' },
  { numeric: 458, name: 'Malaysia', alpha2: 'MY', alpha3: 'MYS' },
  { numeric: 462, name: 'Maldives', alpha2: 'MV', alpha3: 'MDV' },
  { numeric: 466, name: 'Mali', alpha2: 'ML', alpha3: 'MLI' },
  { numeric: 470, name: 'Malta', alpha2: 'MT', alpha3: 'MLT' },
  { numeric: 584, name: 'Marshall Islands', alpha2: 'MH', alpha3: 'MHL' },
  { numeric: 474, name: 'Martinique', alpha2: 'MQ', alpha3: 'MTQ' },
  { numeric: 478, name: 'Mauritania', alpha2: 'MR', alpha3: 'MRT' },
  { numeric: 480, name: 'Mauritius', alpha2: 'MU', alpha3: 'MUS' },
  { numeric: 175, name: 'Mayotte', alpha2: 'YT', alpha3: 'MYT' },
  { numeric: 484, name: 'Mexico', alpha2: 'MX', alpha3: 'MEX' },
  { numeric: 583, name: 'Micronesia, Federated States of', alpha2: 'FM', alpha3: 'FSM' },
  { numeric: 498, name: 'Moldova, Republic of', alpha2: 'MD', alpha3: 'MDA' },
  { numeric: 492, name: 'Monaco', alpha2: 'MC', alpha3: 'MCO' },
  { numeric: 496, name: 'Mongolia', alpha2: 'MN', alpha3: 'MNG' },
  { numeric: 500, name: 'Montserrat', alpha2: 'MS', alpha3: 'MSR' },
  { numeric: 504, name: 'Morocco', alpha2: 'MA', alpha3: 'MAR' },
  { numeric: 508, name: 'Mozambique', alpha2: 'MZ', alpha3: 'MOZ' },
  { numeric: 104, name: 'Myanmar', alpha2: 'MM', alpha3: 'MMR' },
  { numeric: 516, name: 'Namibia', alpha2: 'NA', alpha3: 'NAM' },
  { numeric: 520, name: 'Nauru', alpha2: 'NR', alpha3: 'NRU' },
  { numeric: 524, name: 'Nepal', alpha2: 'NP', alpha3: 'NPL' },
  { numeric: 528, name: 'Netherlands', alpha2: 'NL', alpha3: 'NLD' },
  { numeric: 530, name: 'Netherlands Antilles', alpha2: 'AN', alpha3: 'ANT' },
  { numeric: 540, name: 'New Caledonia', alpha2: 'NC', alpha3: 'NCL' },
  { numeric: 554, name: 'New Zealand', alpha2: 'NZ', alpha3: 'NZL' },
  { numeric: 558, name: 'Nicaragua', alpha2: 'NI', alpha3: 'NIC' },
  { numeric: 562, name: 'Niger', alpha2: 'NE', alpha3: 'NER' },
  { numeric: 566, name: 'Nigeria', alpha2: 'NG', alpha3: 'NGA' },
  { numeric: 570, name: 'Niue', alpha2: 'NU', alpha3: 'NIU' },
  { numeric: 574, name: 'Norfolk Island', alpha2: 'NF', alpha3: 'NFK' },
  { numeric: 580, name: 'Northern Mariana Islands', alpha2: 'MP', alpha3: 'MNP' },
  { numeric: 578, name: 'Norway', alpha2: 'NO', alpha3: 'NOR' },
  { numeric: 512, name: 'Oman', alpha2: 'OM', alpha3: 'OMN' },
  { numeric: 586, name: 'Pakistan', alpha2: 'PK', alpha3: 'PAK' },
  { numeric: 585, name: 'Palau', alpha2: 'PW', alpha3: 'PLW' },
  { numeric: 591, name: 'Panama', alpha2: 'PA', alpha3: 'PAN' },
  { numeric: 598, name: 'Papua New Guinea', alpha2: 'PG', alpha3: 'PNG' },
  { numeric: 600, name: 'Paraguay', alpha2: 'PY', alpha3: 'PRY' },
  { numeric: 604, name: 'Peru', alpha2: 'PE', alpha3: 'PER' },
  { numeric: 608, name: 'Philippines', alpha2: 'PH', alpha3: 'PHL' },
  { numeric: 612, name: 'Pitcairn', alpha2: 'PN', alpha3: 'PCN' },
  { numeric: 616, name: 'Poland', alpha2: 'PL', alpha3: 'POL' },
  { numeric: 620, name: 'Portugal', alpha2: 'PT', alpha3: 'PRT' },
  { numeric: 630, name: 'Puerto Rico', alpha2: 'PR', alpha3: 'PRI' },
  { numeric: 634, name: 'Qatar', alpha2: 'QA', alpha3: 'QAT' },
  { numeric: 638, name: 'Reunion', alpha2: 'RE', alpha3: 'REU' },
  { numeric: 642, name: 'Romania', alpha2: 'RO', alpha3: 'ROU' },
  { numeric: 643, name: 'Russian Federation', alpha2: 'RU', alpha3: 'RUS' },
  { numeric: 646, name: 'Rwanda', alpha2: 'RW', alpha3: 'RWA' },
  { numeric: 654, name: 'Saint Helena', alpha2: 'SH', alpha3: 'SHN' },
  { numeric: 659, name: 'Saint Kitts and Nevis', alpha2: 'KN', alpha3: 'KNA' },
  { numeric: 662, name: 'Saint Lucia', alpha2: 'LC', alpha3: 'LCA' },
  { numeric: 666, name: 'Saint Pierre and Miquelon', alpha2: 'PM', alpha3: 'SPM' },
  { numeric: 670, name: 'Saint Vincent and the Grenadines', alpha2: 'VC', alpha3: 'VCT' },
  { numeric: 882, name: 'Samoa', alpha2: 'WS', alpha3: 'WSM' },
  { numeric: 674, name: 'San Marino', alpha2: 'SM', alpha3: 'SMR' },
  { numeric: 678, name: 'Sao Tome and Principe', alpha2: 'ST', alpha3: 'STP' },
  { numeric: 682, name: 'Saudi Arabia', alpha2: 'SA', alpha3: 'SAU' },
  { numeric: 686, name: 'Senegal', alpha2: 'SN', alpha3: 'SEN' },
  { numeric: 688, name: 'Serbia', alpha2: 'RS', alpha3: 'SRB' },
  { numeric: 690, name: 'Seychelles', alpha2: 'SC', alpha3: 'SYC' },
  { numeric: 694, name: 'Sierra Leone', alpha2: 'SL', alpha3: 'SLE' },
  { numeric: 702, name: 'Singapore', alpha2: 'SG', alpha3: 'SGP' },
  { numeric: 703, name: 'Slovakia', alpha2: 'SK', alpha3: 'SVK' },
  { numeric: 705, name: 'Slovenia', alpha2: 'SI', alpha3: 'SVN' },
  { numeric: 90, name: 'Solomon Islands', alpha2: 'SB', alpha3: 'SLB' },
  { numeric: 706, name: 'Somalia', alpha2: 'SO', alpha3: 'SOM' },
  { numeric: 710, name: 'South Africa', alpha2: 'ZA', alpha3: 'ZAF' },
  {
    numeric: 239,
    name: 'South Georgia and the South Sandwich Islands',
    alpha2: 'GS',
    alpha3: 'SGS',
  },
  { numeric: 724, name: 'Spain', alpha2: 'ES', alpha3: 'ESP' },
  { numeric: 144, name: 'Sri Lanka', alpha2: 'LK', alpha3: 'LKA' },
  { numeric: 736, name: 'Sudan', alpha2: 'SD', alpha3: 'SDN' },
  { numeric: 740, name: 'Suriname', alpha2: 'SR', alpha3: 'SUR' },
  { numeric: 744, name: 'Svalbard and Jan Mayen', alpha2: 'SJ', alpha3: 'SJM' },
  { numeric: 748, name: 'Swaziland', alpha2: 'SZ', alpha3: 'SWZ' },
  { numeric: 752, name: 'Sweden', alpha2: 'SE', alpha3: 'SWE' },
  { numeric: 756, name: 'Switzerland', alpha2: 'CH', alpha3: 'CHE' },
  { numeric: 760, name: 'Syrian Arab Republic', alpha2: 'SY', alpha3: 'SYR' },
  { numeric: 158, name: 'Taiwan, Province of China', alpha2: 'TW', alpha3: 'TWN' },
  { numeric: 762, name: 'Tajikistan', alpha2: 'TJ', alpha3: 'TJK' },
  { numeric: 834, name: 'Tanzania, United Republic of', alpha2: 'TZ', alpha3: 'TZA' },
  { numeric: 764, name: 'Thailand', alpha2: 'TH', alpha3: 'THA' },
  { numeric: 626, name: 'Timor-Leste', alpha2: 'TL', alpha3: 'TLS' },
  { numeric: 768, name: 'Togo', alpha2: 'TG', alpha3: 'TGO' },
  { numeric: 772, name: 'Tokelau', alpha2: 'TK', alpha3: 'TKL' },
  { numeric: 776, name: 'Tonga', alpha2: 'TO', alpha3: 'TON' },
  { numeric: 780, name: 'Trinidad and Tobago', alpha2: 'TT', alpha3: 'TTO' },
  { numeric: 788, name: 'Tunisia', alpha2: 'TN', alpha3: 'TUN' },
  { numeric: 792, name: 'Türkiye, The Republic of', alpha2: 'TR', alpha3: 'TUR' },
  { numeric: 795, name: 'Turkmenistan', alpha2: 'TM', alpha3: 'TKM' },
  { numeric: 796, name: 'Turks and Caicos Islands', alpha2: 'TC', alpha3: 'TCA' },
  { numeric: 798, name: 'Tuvalu', alpha2: 'TV', alpha3: 'TUV' },
  { numeric: 800, name: 'Uganda', alpha2: 'UG', alpha3: 'UGA' },
  { numeric: 804, name: 'Ukraine', alpha2: 'UA', alpha3: 'UKR' },
  { numeric: 784, name: 'United Arab Emirates', alpha2: 'AE', alpha3: 'ARE' },
  { numeric: 275, name: 'Palestine, State of', alpha2: 'PS', alpha3: 'PSE' },
  { numeric: 826, name: 'United Kingdom', alpha2: 'GB', alpha3: 'GBR' },
  { numeric: 840, name: 'United States', alpha2: 'US', alpha3: 'USA' },
  { numeric: 581, name: 'United States Minor Outlying Islands', alpha2: 'UM', alpha3: 'UMI' },
  { numeric: 858, name: 'Uruguay', alpha2: 'UY', alpha3: 'URY' },
  { numeric: 860, name: 'Uzbekistan', alpha2: 'UZ', alpha3: 'UZB' },
  { numeric: 548, name: 'Vanuatu', alpha2: 'VU', alpha3: 'VUT' },
  { numeric: 862, name: 'Venezuela', alpha2: 'VE', alpha3: 'VEN' },
  { numeric: 704, name: 'Viet Nam', alpha2: 'VN', alpha3: 'VNM' },
  { numeric: 92, name: 'Virgin Islands, British', alpha2: 'VG', alpha3: 'VGB' },
  { numeric: 850, name: 'Virgin Islands, U.s.', alpha2: 'VI', alpha3: 'VIR' },
  { numeric: 876, name: 'Wallis and Futuna', alpha2: 'WF', alpha3: 'WLF' },
  { numeric: 732, name: 'Western Sahara', alpha2: 'EH', alpha3: 'ESH' },
  { numeric: 887, name: 'Yemen', alpha2: 'YE', alpha3: 'YEM' },
  { numeric: 894, name: 'Zambia', alpha2: 'ZM', alpha3: 'ZMB' },
  { numeric: 716, name: 'Zimbabwe', alpha2: 'ZW', alpha3: 'ZWE' },
  { numeric: 499, name: 'Montenegro', alpha2: 'ME', alpha3: 'MNE' },
  { numeric: 0, name: 'Kosovo', alpha2: 'XK', alpha3: 'XKX' }, // Note: XK is user-assigned
  { numeric: 248, name: 'Aland Islands', alpha2: 'AX', alpha3: 'ALA' },
  { numeric: 535, name: 'Bonaire, Sint Eustatius and Saba', alpha2: 'BQ', alpha3: 'BES' },
  { numeric: 531, name: 'Curacao', alpha2: 'CW', alpha3: 'CUW' },
  { numeric: 831, name: 'Guernsey', alpha2: 'GG', alpha3: 'GGY' },
  { numeric: 833, name: 'Isle of Man', alpha2: 'IM', alpha3: 'IMN' },
  { numeric: 832, name: 'Jersey', alpha2: 'JE', alpha3: 'JEY' },
  { numeric: 652, name: 'Saint Barthelemy', alpha2: 'BL', alpha3: 'BLM' },
  { numeric: 663, name: 'Saint Martin', alpha2: 'MF', alpha3: 'MAF' },
  { numeric: 534, name: 'Sint Maarten', alpha2: 'SX', alpha3: 'SXM' },
  { numeric: 728, name: 'South Sudan', alpha2: 'SS', alpha3: 'SSD' },
  { numeric: 166, name: 'Cocos (Keeling) Islands', alpha2: 'CC', alpha3: 'CCK' },
];
