import { SignJWT, importPKCS8 } from 'jose';

export interface AppleClientSecretOptions {
  /** Apple Developer Team ID (Membership details). */
  teamId: string;
  /** Key ID of a key with Sign in with Apple enabled (Certificates, Identifiers & Profiles → Keys). */
  keyId: string;
  /** Contents of that key's `.p8` file: a PKCS#8 PEM. */
  privateKey: string;
  /** Lifetime of each signed secret, in seconds. Apple caps it at six months. Default: one hour. */
  expiresIn?: number;
  /** Re-sign once fewer than this many seconds remain, so a cached secret never reaches Apple expired. Default: five minutes. */
  renewBefore?: number;
}

/**
 * Sign in with Apple has no static client secret: the secret is a JWT the server signs with its
 * Sign in with Apple key (ES256, `iss` = team, `sub` = client id, `aud` = appleid.apple.com), and
 * a team signs one per client id — the app's bundle id and the web Services ID share the key and
 * differ only in `sub`.
 *
 * Returns `clientId => secret`, signing on demand and caching per client id until `renewBefore`
 * seconds before expiry, so the secret can be minted by the server at runtime (an
 * `OAuth2ClientConfig.registration` function) instead of being generated by hand and stored, and
 * rotated, as a static secret.
 */
export function createAppleClientSecret(options: AppleClientSecretOptions) {
  const { teamId, keyId, privateKey, expiresIn = 3600, renewBefore = 300 } = options;
  if (renewBefore >= expiresIn) {
    throw new Error('renewBefore must be shorter than expiresIn');
  }

  // The import is cached as a promise so concurrent first calls share one; a failed import is
  // dropped so the next call retries instead of failing forever.
  let key: Promise<CryptoKey> | undefined;
  const cache = new Map<string, { secret: string; exp: number }>();

  function getKey() {
    key ??= importPKCS8(privateKey, 'ES256').catch((error: unknown) => {
      key = undefined;
      throw error;
    });
    return key;
  }

  return async function appleClientSecret(clientId: string): Promise<string> {
    const now = Math.floor(Date.now() / 1000);
    const cached = cache.get(clientId);
    if (cached && cached.exp - now > renewBefore) return cached.secret;

    const exp = now + expiresIn;
    const secret = await new SignJWT({})
      .setProtectedHeader({ alg: 'ES256', kid: keyId })
      .setIssuer(teamId)
      .setSubject(clientId)
      .setAudience('https://appleid.apple.com')
      .setIssuedAt(now)
      .setExpirationTime(exp)
      .sign(await getKey());
    cache.set(clientId, { secret, exp });
    return secret;
  };
}
