-- Journey engine data plane on Postgres (PostgresJourneyStore). Table names are
-- `<prefix><name>` with the default prefix `workflow_`; put them in whatever
-- schema the store is configured with. This file is the reference DDL — a
-- project with its own migration tooling (drizzle, prisma, …) mirrors it there.

-- Raw event log. Every count- and window-based condition reads it, so a
-- duplicated row silently changes a journey's behaviour; event_id is the
-- occurrence's identity, chosen by the sender (a retrying HTTP client, or the
-- interpreter's send_event step), and its unique index makes a second delivery
-- of the same occurrence a no-op. The row key itself stays a UUID v7.
CREATE TABLE IF NOT EXISTS workflow_event (
  id       uuid PRIMARY KEY,                      -- UUID v7, generated by the store
  event_id text NOT NULL,                         -- sender-chosen occurrence id
  user_id  text NOT NULL,
  name    text NOT NULL,
  ts      timestamptz NOT NULL,
  payload jsonb NOT NULL,
  CONSTRAINT workflow_event_uuid_v7 CHECK (substring(id::text, 15, 1) = '7')
);
CREATE UNIQUE INDEX IF NOT EXISTS workflow_event_event_id_idx ON workflow_event (event_id);
CREATE INDEX IF NOT EXISTS workflow_event_user_id_name_ts_idx ON workflow_event (user_id, name, ts);

CREATE TABLE IF NOT EXISTS workflow_profile (
  user_id text PRIMARY KEY,
  props   jsonb NOT NULL
);

-- Deployed definitions: segment conditions (resolved by name at evaluation time)
-- and the trigger routes; workflow bodies are content-addressed in workflow_ir.
CREATE TABLE IF NOT EXISTS workflow_segment (
  name      text PRIMARY KEY,
  condition jsonb NOT NULL,
  hash      text NOT NULL
);

-- Event-trigger routes; "where" gates on the event payload, filter on the profile.
CREATE TABLE IF NOT EXISTS workflow_trigger (
  workflow text PRIMARY KEY,
  hash     text NOT NULL,
  event    text NOT NULL,
  "where"  jsonb,
  filter   jsonb
);
CREATE INDEX IF NOT EXISTS workflow_trigger_event_idx ON workflow_trigger (event);

CREATE TABLE IF NOT EXISTS workflow_segment_trigger (
  workflow text PRIMARY KEY,
  hash     text NOT NULL,
  segment  text NOT NULL
);
CREATE INDEX IF NOT EXISTS workflow_segment_trigger_segment_idx ON workflow_segment_trigger (segment);

-- Lazily maintained membership of trigger-routed segments (see router.ts).
CREATE TABLE IF NOT EXISTS workflow_segment_member (
  segment text NOT NULL,
  user_id text NOT NULL,
  ts      timestamptz NOT NULL,
  PRIMARY KEY (segment, user_id)
);

-- Entry ledger: once policy (the primary key) + instance addressing + version pin audit.
CREATE TABLE IF NOT EXISTS workflow_entry (
  workflow    text NOT NULL,
  user_id     text NOT NULL,
  instance_id text NOT NULL,
  hash        text NOT NULL,
  status      text NOT NULL,
  ts          timestamptz NOT NULL,
  PRIMARY KEY (workflow, user_id)
);
CREATE INDEX IF NOT EXISTS workflow_entry_instance_id_idx ON workflow_entry (instance_id);

-- wait_until wake routing: the primary key makes the interpreter's repeated
-- subscribe (one subscribe arms one wake-up) idempotent.
CREATE TABLE IF NOT EXISTS workflow_subscription (
  user_id     text NOT NULL,
  event       text NOT NULL,
  wake_handle text NOT NULL,
  ts          timestamptz NOT NULL,
  PRIMARY KEY (wake_handle, event)
);
CREATE INDEX IF NOT EXISTS workflow_subscription_user_id_event_idx ON workflow_subscription (user_id, event);

-- Workflow bodies (WorkflowIR), content-addressed: what KV held in the D1 store.
CREATE TABLE IF NOT EXISTS workflow_ir (
  content_hash text PRIMARY KEY,
  ir           jsonb NOT NULL
);
